// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title SignalRegistry
 * @dev Records trade signals generated by the GhostWhale AI council on-chain.
 */
contract SignalRegistry is Ownable {
    struct Signal {
        string signalId;
        string token;
        string direction; // BUY / SELL / HOLD
        uint256 confidence; // basis points (e.g. 8500 = 85%)
        string reasoningHash; // Hash of the detailed reasoning text
        uint256 timestamp;
        bool exists;
    }

    mapping(string => Signal) private _signals;
    string[] private _signalIds;

    event SignalRegistered(
        string indexed signalId,
        string token,
        string direction,
        uint256 confidence,
        uint256 timestamp
    );

    constructor() Ownable(msg.sender) {}

    function registerSignal(
        string calldata signalId,
        string calldata token,
        string calldata direction,
        uint256 confidence,
        string calldata reasoningHash
    ) external onlyOwner {
        require(!_signals[signalId].exists, "Signal already registered");

        _signals[signalId] = Signal({
            signalId: signalId,
            token: token,
            direction: direction,
            confidence: confidence,
            reasoningHash: reasoningHash,
            timestamp: block.timestamp,
            exists: true
        });
        _signalIds.push(signalId);

        emit SignalRegistered(signalId, token, direction, confidence, block.timestamp);
    }

    function getSignal(string calldata signalId) external view returns (Signal memory) {
        require(_signals[signalId].exists, "Signal does not exist");
        return _signals[signalId];
    }

    function getSignalCount() external view returns (uint256) {
        return _signalIds.length;
    }

    function getSignalIdAt(uint256 index) external view returns (string memory) {
        require(index < _signalIds.length, "Index out of bounds");
        return _signalIds[index];
    }
}
